### ISSUE TITLE
Xcode 9 build fail: Cannot invoke method hashCode() on null object

### ISSUE THREAD

**Issue by adil-hussain-84** [openbakery/gradle-xcodePlugin#369] opened 2017-09-25 16:14 UTC
I've got an iOS Application and Framework project using this plugin. I updated my version of Xcode to Xcode 9.0 and I can no longer build the projects using this plugin. The builds fail pretty quickly with an exception with the following message:

    Execution failed for task ':iOS:xcodebuild'.
     > Cannot invoke method hashCode() on null object

Anyone else experiencing this?

**Comment by adil-hussain-84** [comment] 2017-09-25 16:16
My `build.gradle` file looks like this btw:

```plugins {
    id 'org.openbakery.xcode-plugin' version '0.15.0'
}

xcodebuild {
    destination = ['iPhone 7']
    scheme = 'SomeProject'
    simulator = false // value = true or false, default = true
    target = 'SomeProject'
    type = 'iOS'
    workspace = 'SomeProject.xcworkspace'
}```

**Comment by adil-hussain-84** [comment] 2017-09-25 16:21
Not sure if it's significant but I just ran the Gradle build with the debug option and I see this in the logs:

    17:18:11.631 [DEBUG] [org.openbakery.xcode.Xcode] create xcode with version null
    17:18:11.631 [DEBUG] [org.gradle.api.Task] using xcode Xcode{xcodePath='null', version=null}

**Comment by igorkotkovets** [comment] 2017-09-26 07:19
The issue is related to reported bug about [Xcode's simulator output](https://github.com/openbakery/gradle-xcodePlugin/issues/368)
Fixed in `develop` version.
`classpath "org.openbakery:xcode-plugin:0.15.1.develop.+"`

**Comment by adil-hussain-84** [comment] 2017-09-26 09:49
Thanks @igorkotkovets. Changing my project to use the development version of this plugin has resolved the issue.

For anyone reading this not sure how to use the development version, declare the plugin's repository and classpath in your root-level `build.gradle` file as follows...

    buildscript {
        repositories {
            maven {
                url('http://repository.openbakery.org/')
            }
        }
        dependencies {
            classpath "org.openbakery:xcode-plugin:0.15.1.develop.+"
        }
    }

... and apply the plugin in the `build.gradle` of your iOS project as follows...

    apply plugin: "org.openbakery.xcode-plugin"

**Closed** 2017-09-26 12:20 UTC

**Comment by themcaguy** [comment] 2017-12-20 13:12
I am also facing the same problem, I just want to know the Gradle version to support the following openbakery version: org.openbakery:xcode-plugin:0.15.1.develop.+

Anyone??

**Comment by adil-hussain-84** [comment] 2017-12-21 14:53
@themcaguy: I'm using the development version of this plugin with Gradle version 4.3.1 and it's working fine for me.

**Comment by themcaguy** [comment] 2017-12-22 05:03
@adil-hussain-84: Thanks for reply. I tried the solution you have mentioned but doesn't worked for me.
I'm using the 0.15.+ version of this plugin with Gradle version 4.2 and it's working fine for me with following build.gradle script.

buildscript {
   repositories {
       maven {
         url ('http://repository.openbakery.org/')
        }
        **mavenCentral()**
   }
   dependencies {
       classpath "org.openbakery:xcode-plugin:0.15.+"
   }
}
apply plugin: "org.openbakery.xcode-plugin"
