### ISSUE TITLE
package tasks fails with NullPointerException

### ISSUE THREAD

**Issue by emartynov** [openbakery/gradle-xcodePlugin#175] opened 2015-04-23 13:06 UTC
Hi Rene,

I have next stacktrace:
```
Caused by: java.lang.NullPointerException
	at org.openbakery.InfoPlistModifyTask.prepare(InfoPlistModifyTask.groovy:35)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
```

If I run `gradle package`

**Comment by renep** [comment] 2015-04-23 13:18
Looks like the info plist was not set. 
The InfoPlistModifyTask has a dependency to the XcodeConfigTask, and in the XcodeConfigTask the infoplist should be set. 

if you run gradle with `-i` you should see first a ```Parse project file: ``` output and then a ```infoPlist: ...``` output where the infoplist is displayed that should be modified.

Maybe in the build configuration of the xcode project the info plist was not set.

(I have added a better error message in my code)

**Comment by emartynov** [comment] 2015-04-23 13:31
Is it because 6.3.1 install?

Here is partially my output:
```
:xcodebuildConfig
Executing task ':xcodebuildConfig' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Parse project file: /Users/emartynov/Development/Projects/MindDistrict/ios-minddistrict/minddistrict.xcodeproj/project.pbxproj
infoPlist: null
Xcode 6.3.1
```

**Comment by renep** [comment] 2015-04-23 13:42
6.3.1 should not be the issue because it work with my project

try:
```
gradle infoPlistModify --debug | grep org.openbakery.XcodeProjectFile
```
the output are all the key that are fetch from the project file

And here should be an entry like:
```
String objects.A79CC9811898F4910018BAB5.buildSettings.INFOPLIST_FILE=Resources/Info.plist
```

**Comment by renep** [comment] 2015-04-23 13:46
You you check your target in Xcode if the Info.plist File set?

**Comment by emartynov** [comment] 2015-04-23 13:54
Here is output:
```
15:48:17.712 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.{buildConfiguration}.buildSettings.SDKROOT=null
15:48:17.712 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.2AAEF56C189FF98400C4EEE6.buildSettings.SDKROOT=iphoneos
15:48:17.713 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.{buildConfiguration}.buildSettings.TARGETED_DEVICE_FAMILY=null
15:48:17.713 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.null.buildSettings.INFOPLIST_FILE=null
15:48:17.713 [INFO] [org.openbakery.XcodeProjectFile] infoPlist: null
```
Three targets have plist set but one of plist has whitepace in filename

**Comment by renep** [comment] 2015-04-23 14:20
is you xcodebuild.target set on the build.gradle file?

**Comment by emartynov** [comment] 2015-04-23 14:44
Yes, target is set but plist file for this target has absolute path and whitespace in filename

**Comment by renep** [comment] 2015-04-23 15:01
the problem is not the infoPlist 
the problem is already here:
```15:48:17.713 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.null.buildSettings.INFOPLIST_FILE=null```

objects.null.buildSettings -> there should not be a null. Is it possible that you have specified a target that does not exist.

**Comment by emartynov** [comment] 2015-04-23 15:25
My apologises! I changed schema to have name without whitespace because of coverage tool. But I also changed in build.gradle target by mistake. After fix I don't see NPE anymore. Thank you!

However I have now another error :)

**Comment by renep** [comment] 2015-04-23 15:27
No Problem.
I have added some checks when processing the xcode project file that should give better error messages  in that case ;-)

**Comment by emartynov** [comment] 2015-04-23 15:27
Should I create another issue?

**Comment by renep** [comment] 2015-04-23 15:32
I have discussed this the other day with a colleague. Until now the output direction is search for a *.app and takes the first that was found. So if you build multiple apps you will have a problem. So run a clean first, to make sure that the proper app is picked.

**Comment by emartynov** [comment] 2015-04-23 15:44
The problem is not with clean. I have app specified in target but archive is specifically looking for another app. Which was not built.

**Comment by renep** [comment] 2015-04-24 06:04
My comment about that the *.app is search is not entirely true. This is done so at the package task, but not on the archive task.
At archive the path is created and here the App name is created from the output path and the bundle name:
```
	String getBundleName() {
		if (bundleName != null) {
			return bundleName
		}
		bundleName = getValueFromInfoPlist("CFBundleName")

		bundleName = variableResolver.resolve(bundleName);

		if (StringUtils.isEmpty(bundleName)) {
			bundleName = this.productName
		}
		return bundleName
	}
```

You can set the bundleName in your build.gradle file with xcodebuild.bundleName, but I would be great to know why it is not properly set in your project.

You see in the code that first the CFBundleName is taken, and if this value is a variable, it is tried to be resolved. Here the ${PRODUCT_NAME} is the only value is properly processed. Maybe you have in your config another variable.

**Comment by emartynov** [comment] 2015-04-24 07:33
Can you point me to direction what to do?

I checked both plist files and both of them have:
```
        <key>CFBundleName</key>
        <string>${PRODUCT_NAME}</string>
```
I can specify it in `build.gradle` but if you don't mind I would like to avoid it.

**Comment by renep** [comment] 2015-04-24 08:05
Normally this should work.
If you run
```
gradle infoPlistModify --debug | grep org.openbakery.XcodeProjectFile
```
you should see the productName that is parsed from the project file e.g.:

```
09:59:37.016 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.A7E24DEF13FA56B9007B3FF9.productName=MyApp
```

This value comes from the target, so if you search for `Product Name` at the target you should see the same value.
Can you check that, so that we find out what the problem is. Maybe I have missed something when processing the projectName.

**Comment by emartynov** [comment] 2015-04-24 09:12
Interesting. Here is output:
```
10:12:43.650 [DEBUG] [org.openbakery.XcodeProjectFile] String rootObject=2AAEF530189FF98400C4EEE6
10:12:43.650 [DEBUG] [org.openbakery.XcodeProjectFile] rootObjectKey 2AAEF530189FF98400C4EEE6
10:12:43.651 [DEBUG] [org.openbakery.XcodeProjectFile] List objects.2AAEF530189FF98400C4EEE6.targets=[2AAEF537189FF98400C4EEE6, 2A37C8E3195D96AC0003B4E5, 2AAEF55B189FF98400C4EEE6]
10:12:43.654 [DEBUG] [org.openbakery.XcodeProjectFile] List objects.2AAEF530189FF98400C4EEE6.targets=[2AAEF537189FF98400C4EEE6, 2A37C8E3195D96AC0003B4E5, 2AAEF55B189FF98400C4EEE6]
10:12:43.655 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.2AAEF537189FF98400C4EEE6.name=minddistrict
10:12:43.655 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.2A37C8E3195D96AC0003B4E5.name=minddistrict develop
10:12:43.655 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.2A37C8E3195D96AC0003B4E5.productName=minddistrict
10:12:43.656 [DEBUG] [org.openbakery.XcodeProjectFile] List objects.2AAEF530189FF98400C4EEE6.targets=[2AAEF537189FF98400C4EEE6, 2A37C8E3195D96AC0003B4E5, 2AAEF55B189FF98400C4EEE6]
10:12:43.656 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.2AAEF537189FF98400C4EEE6.name=minddistrict
10:12:43.656 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.2A37C8E3195D96AC0003B4E5.name=minddistrict develop
10:12:43.656 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.2A37C8E3195D96AC0003B4E5.productType=com.apple.product-type.application
10:12:43.656 [DEBUG] [org.openbakery.XcodeProjectFile] List objects.2AAEF530189FF98400C4EEE6.targets=[2AAEF537189FF98400C4EEE6, 2A37C8E3195D96AC0003B4E5, 2AAEF55B189FF98400C4EEE6]
10:12:43.657 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.2AAEF537189FF98400C4EEE6.name=minddistrict
10:12:43.657 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.2A37C8E3195D96AC0003B4E5.name=minddistrict develop
10:12:43.657 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.2A37C8E3195D96AC0003B4E5.buildConfigurationList=2A37C97F195D96AC0003B4E5
10:12:43.657 [DEBUG] [org.openbakery.XcodeProjectFile] List objects.2A37C97F195D96AC0003B4E5.buildConfigurations=[2A37C980195D96AC0003B4E5, 2A37C981195D96AC0003B4E5]
10:12:43.657 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.2A37C980195D96AC0003B4E5.name=Debug
10:12:43.658 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.2A37C981195D96AC0003B4E5.name=Release
10:12:43.658 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.2AAEF530189FF98400C4EEE6.buildConfigurationList=2AAEF533189FF98400C4EEE6
10:12:43.658 [DEBUG] [org.openbakery.XcodeProjectFile] List objects.2AAEF533189FF98400C4EEE6.buildConfigurations=[2AAEF56B189FF98400C4EEE6, 2AAEF56C189FF98400C4EEE6]
10:12:43.658 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.2AAEF56B189FF98400C4EEE6.name=Debug
10:12:43.658 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.2AAEF56C189FF98400C4EEE6.name=Release
10:12:43.658 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.{buildConfiguration}.buildSettings.SDKROOT=null
10:12:43.658 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.2AAEF56C189FF98400C4EEE6.buildSettings.SDKROOT=iphoneos
10:12:43.659 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.{buildConfiguration}.buildSettings.TARGETED_DEVICE_FAMILY=null
10:12:43.659 [DEBUG] [org.openbakery.XcodeProjectFile] String objects.2A37C981195D96AC0003B4E5.buildSettings.INFOPLIST_FILE=$(SRCROOT)/minddistrict develop-Info.plist
10:12:43.660 [INFO] [org.openbakery.XcodeProjectFile] infoPlist: $(SRCROOT)/minddistrict develop-Info.plist
```
And here is screenshot from xcode:
![screenshot 2015-04-24 11 04 32](https://cloud.githubusercontent.com/assets/295424/7315855/c449c602-ea71-11e4-93ef-b5c921ab0c0e.png)
![screenshot 2015-04-24 11 04 41](https://cloud.githubusercontent.com/assets/295424/7315865/cfa1f326-ea71-11e4-919e-b3ce2f81734b.png)

But in project file I see next:
```
			name = "minddistrict develop";
			productName = minddistrict;
			productReference = 2A37C982195D96AC0003B4E5 /* minddistrict-develop.app */;
			productType = "com.apple.product-type.application";
```
And another mention later:
```
/* Begin XCBuildConfiguration section */
		2A37C980195D96AC0003B4E5 /* Debug */ = {
			isa = XCBuildConfiguration;
			baseConfigurationReference = DBB38D74F1AED66EC639DEF3 /* Pods.debug.xcconfig */;
			buildSettings = {
				ASSETCATALOG_COMPILER_APPICON_NAME = "AppIcon-develop";
				ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME = LaunchImage;
				CODE_SIGN_IDENTITY = "iPhone Developer";
				"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";
				CODE_SIGN_RESOURCE_RULES_PATH = "$(SDKROOT)/ResourceRules.plist";
				FRAMEWORK_SEARCH_PATHS = "$(inherited)";
				GCC_PRECOMPILE_PREFIX_HEADER = YES;
				GCC_PREFIX_HEADER = "minddistrict/minddistrict-Prefix.pch";
				INFOPLIST_FILE = "$(SRCROOT)/minddistrict develop-Info.plist";
				IPHONEOS_DEPLOYMENT_TARGET = 6.1;
				LIBRARY_SEARCH_PATHS = (
					"$(inherited)",
					"$(PROJECT_DIR)/Flurry",
				);
				PRODUCT_NAME = "minddistrict-develop";
				PROVISIONING_PROFILE = "";
				TARGETED_DEVICE_FAMILY = "1,2";
				USER_HEADER_SEARCH_PATHS = "\"${PROJECT_DIR}/Pods\"/**";
				WRAPPER_EXTENSION = app;
			};
			name = Debug;
		};
		2A37C981195D96AC0003B4E5 /* Release */ = {
			isa = XCBuildConfiguration;
			baseConfigurationReference = CFA3CF6E68F9145CC1709E82 /* Pods.release.xcconfig */;
			buildSettings = {
				ASSETCATALOG_COMPILER_APPICON_NAME = "AppIcon-develop";
				ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME = LaunchImage;
				CODE_SIGN_IDENTITY = "iPhone Developer";
				"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";
				CODE_SIGN_RESOURCE_RULES_PATH = "$(SDKROOT)/ResourceRules.plist";
				FRAMEWORK_SEARCH_PATHS = "$(inherited)";
				GCC_PRECOMPILE_PREFIX_HEADER = YES;
				GCC_PREFIX_HEADER = "minddistrict/minddistrict-Prefix.pch";
				INFOPLIST_FILE = "$(SRCROOT)/minddistrict develop-Info.plist";
				IPHONEOS_DEPLOYMENT_TARGET = 6.1;
				LIBRARY_SEARCH_PATHS = (
					"$(inherited)",
					"$(PROJECT_DIR)/Flurry",
				);
				PRODUCT_NAME = "minddistrict-develop";
				PROVISIONING_PROFILE = "";
				TARGETED_DEVICE_FAMILY = "1,2";
				USER_HEADER_SEARCH_PATHS = "\"${PROJECT_DIR}/Pods\"/**";
				WRAPPER_EXTENSION = app;
			};
			name = Release;
		};
```

**Comment by renep** [comment] 2015-04-24 09:44
Looks like im using the wrong product name settings from the project file. the 'productName' seams not to be the proper one, I have to use the `PRODUCT_NAME` as it seams.

**Comment by renep** [comment] 2015-04-24 11:52
I have prepared a test version with (hopefully) a fix: `0.10.3-test4`

Note: the identifier has changed from `xcodeplugin` to: `org.openbakery.xcodeplugin` so you need now:
`apply plugin: 'org.openbakery.xcodeplugin'`

The reasons is that the 0.10.3 version is already deployed on the https://plugins.gradle.org and for this I had to change the identifier.

**Comment by emartynov** [comment] 2015-04-24 11:58
Just tried and it worked. Thanks!

I got warning about capitalised letter in plugin name description. But everything else went smooth.
As suggestion would it better to have `xcode-plugin`? But as for me it is already not same functionality as xcode has

**Comment by renep** [comment] 2015-04-24 12:19
I have change the `xcodePlugin` to be `xcodeplugin` to match the new id `org.openbakery.xcodeplugin`. The dash would have been not a bad idea, but I already publish a version to plugins.gradle.org, so I do not want to change it (again)

**Comment by renep** [comment] 2015-04-24 12:19
I'll close this now.

**Closed by renep** 2015-04-24 12:19 UTC

**Comment by emartynov** [comment] 2015-04-28 14:37
Rene, when 0.10.4 will be released?

**Comment by renep** [comment] 2015-04-28 14:39
It will be 0.11 ;-) 
I hope this week.
